"""Integration tests for AI quote generation endpoint."""

from decimal import Decimal
from typing import Any
from unittest.mock import AsyncMock, patch
from uuid import uuid4

import pytest
from httpx import AsyncClient
from mtp_shared import BoQGenerateResponse, BoQLineItem


async def _create_tenant(client: AsyncClient, slug: str) -> dict[str, Any]:
    response = await client.post("/tenants", json={"slug": slug, "name": f"{slug} Ltd"})
    assert response.status_code == 201
    return response.json()  # type: ignore[no-any-return]


async def _create_contact(client: AsyncClient, tenant_id: str, name: str) -> dict[str, Any]:
    response = await client.post(
        "/contacts",
        headers={"X-Tenant-ID": tenant_id},
        json={"name": name, "email": f"{name.lower().replace(' ', '.')}@example.com"},
    )
    assert response.status_code == 201
    return response.json()  # type: ignore[no-any-return]


@pytest.mark.asyncio
async def test_generate_quote_creates_draft_quote(client: AsyncClient) -> None:
    tenant = await _create_tenant(client, f"sparky-{uuid4().hex[:8]}")
    contact = await _create_contact(client, tenant["id"], "AI Customer")

    retrieved = [
        {
            "code": "ELEC-SOCKET-ADD",
            "description": "Install one additional double socket",
            "unit": "each",
            "unit_price": "85.00",
            "category": "Sockets",
        }
    ]
    generated = {
        "line_items": [{"code": "ELEC-SOCKET-ADD", "quantity": 2, "reason": "two new sockets"}],
        "notes": "Generated by AI",
    }

    with (
        patch("app.routers.quotes.search_cost_items", new=AsyncMock(return_value=retrieved)),
        patch(
            "app.routers.quotes.generate_quote_from_prompt", new=AsyncMock(return_value=generated)
        ),
    ):
        response = await client.post(
            "/quotes/generate",
            headers={"X-Tenant-ID": tenant["id"]},
            json={
                "contact_id": contact["id"],
                "description": "I need two extra double sockets installed",
                "use_ocerp": False,
            },
        )

    assert response.status_code == 201
    quote = response.json()
    assert quote["contact_id"] == contact["id"]
    assert quote["status"] == "draft"
    assert quote["subtotal"] == "170.00"
    assert quote["vat_amount"] == "34.00"
    assert quote["total"] == "204.00"
    assert len(quote["line_items"]) == 1
    assert quote["line_items"][0]["quantity"] == "2"


@pytest.mark.asyncio
async def test_generate_quote_from_lead_links_back(client: AsyncClient) -> None:
    """Generating from a quote request builds the description from the captured
    data, reuses its contact, and links the lead to the resulting quote."""
    tenant = await _create_tenant(client, f"sparky-{uuid4().hex[:8]}")

    # Submit a lead through the public (homeowner) endpoint.
    submit = await client.post(
        f"/businesses/{tenant['slug']}/quote-requests",
        json={
            "contact": {
                "name": "Lead Owner",
                "email": "lead.owner@example.com",
                "postcode": "M1 1AA",
            },
            "category": "consumer_unit",
            "title": "Consumer unit upgrade",
            "raw_text": "Old fuse board keeps tripping",
        },
    )
    assert submit.status_code == 201, submit.text
    lead_id = submit.json()["id"]

    retrieved = [
        {
            "code": "ELEC-CU-UPGRADE",
            "description": "Upgrade consumer unit",
            "unit": "each",
            "unit_price": "480.00",
            "category": "Consumer Units",
        }
    ]
    generated = {"line_items": [{"code": "ELEC-CU-UPGRADE", "quantity": 1}], "notes": ""}

    captured: dict[str, str] = {}

    async def _fake_generate(**kwargs: Any) -> dict[str, Any]:
        captured["description"] = kwargs["job_description"]
        return generated

    with (
        patch("app.routers.quotes.search_cost_items", new=AsyncMock(return_value=retrieved)),
        patch(
            "app.routers.quotes.generate_quote_from_prompt",
            new=AsyncMock(side_effect=_fake_generate),
        ),
    ):
        response = await client.post(
            "/quotes/generate",
            headers={"X-Tenant-ID": tenant["id"]},
            json={"quote_request_id": lead_id, "use_ocerp": False},
        )

    assert response.status_code == 201, response.text
    quote = response.json()
    # Description was built from the lead (category + raw text).
    assert "consumer_unit" in captured["description"] or "Consumer unit" in captured["description"]
    assert "fuse board" in captured["description"]
    # The quote reuses the lead's contact.
    assert quote["customer"]["name"] == "Lead Owner"

    # The lead is now linked to the generated quote.
    lead = await client.get(f"/quote-requests/{lead_id}", headers={"X-Tenant-ID": tenant["id"]})
    assert lead.status_code == 200
    lead_body = lead.json()
    assert lead_body["quote_id"] == quote["id"]
    assert lead_body["status"] == "converted_to_quote"


@pytest.mark.asyncio
async def test_generate_quote_creates_contact_when_not_provided(client: AsyncClient) -> None:
    tenant = await _create_tenant(client, f"sparky-{uuid4().hex[:8]}")

    retrieved = [
        {
            "code": "ELEC-CU-UPGRADE",
            "description": "Upgrade consumer unit",
            "unit": "each",
            "unit_price": "480.00",
            "category": "Consumer Units",
        }
    ]
    generated = {
        "line_items": [{"code": "ELEC-CU-UPGRADE", "quantity": 1}],
        "notes": "",
    }

    with (
        patch("app.routers.quotes.search_cost_items", new=AsyncMock(return_value=retrieved)),
        patch(
            "app.routers.quotes.generate_quote_from_prompt", new=AsyncMock(return_value=generated)
        ),
    ):
        response = await client.post(
            "/quotes/generate",
            headers={"X-Tenant-ID": tenant["id"]},
            json={
                "description": "Upgrade my consumer unit",
                "customer_name": "New Lead",
                "customer_email": "lead@example.com",
                "use_ocerp": False,
            },
        )

    assert response.status_code == 201
    quote = response.json()
    assert quote["tenant_id"] == tenant["id"]
    assert Decimal(quote["total"]) == Decimal("576.00")


@pytest.mark.asyncio
async def test_generate_quote_returns_503_when_ai_not_configured(client: AsyncClient) -> None:
    tenant = await _create_tenant(client, f"sparky-{uuid4().hex[:8]}")
    contact = await _create_contact(client, tenant["id"], "AI Customer")

    with (
        patch(
            "app.routers.quotes.search_cost_items",
            new=AsyncMock(side_effect=RuntimeError("OPENAI_API_KEY is not configured")),
        ),
    ):
        response = await client.post(
            "/quotes/generate",
            headers={"X-Tenant-ID": tenant["id"]},
            json={
                "contact_id": contact["id"],
                "description": "I need a new socket",
                "use_ocerp": False,
            },
        )

    assert response.status_code == 503


@pytest.mark.skip(reason="OCERP/BoQ is parked for the mobile-pivot MVP")
@pytest.mark.asyncio
async def test_generate_quote_with_ocerp(client: AsyncClient) -> None:
    tenant = await _create_tenant(client, f"sparky-{uuid4().hex[:8]}")
    contact = await _create_contact(client, tenant["id"], "OCERP Customer")

    boq_response = BoQGenerateResponse(
        line_items=[
            BoQLineItem(
                code="ELEC-CU-UPGRADE",
                description="Upgrade consumer unit",
                unit="each",
                quantity=Decimal("1"),
                labour_hours=Decimal("2.00"),
                labour_rate=Decimal("45.00"),
                labour_total=Decimal("90.00"),
                material_cost=Decimal("390.00"),
                material_total=Decimal("390.00"),
                plant_cost=Decimal("0.00"),
                plant_total=Decimal("0.00"),
                unit_price=Decimal("480.00"),
                total=Decimal("480.00"),
            )
        ],
        subtotal=Decimal("480.00"),
        vat_amount=Decimal("96.00"),
        total=Decimal("576.00"),
        confidence=Decimal("1.0"),
        notes="CU upgrade BoQ",
        standard="nrm1",
    )

    with patch(
        "app.clients.ocerp.OCERPClient.generate_boq",
        new=AsyncMock(return_value=boq_response),
    ):
        response = await client.post(
            "/quotes/generate",
            headers={"X-Tenant-ID": tenant["id"]},
            json={
                "contact_id": contact["id"],
                "description": "Upgrade consumer unit",
                "use_ocerp": True,
            },
        )

    assert response.status_code == 201
    quote = response.json()
    assert quote["contact_id"] == contact["id"]
    assert quote["status"] == "draft"
    assert Decimal(quote["total"]) == Decimal("576.00")
    assert len(quote["line_items"]) == 1
    assert quote["line_items"][0]["description"] == "Upgrade consumer unit"
    assert quote["bill_of_quantities"] is not None
    assert Decimal(quote["bill_of_quantities"]["total"]) == Decimal("576.00")
    assert len(quote["bill_of_quantities"]["line_items"]) == 1
    boq_line = quote["bill_of_quantities"]["line_items"][0]
    assert boq_line["code"] == "ELEC-CU-UPGRADE"
    assert Decimal(boq_line["labour_total"]) == Decimal("90.00")
    assert Decimal(boq_line["material_total"]) == Decimal("390.00")


@pytest.mark.skip(reason="OCERP/BoQ is parked for the mobile-pivot MVP")
@pytest.mark.asyncio
async def test_generate_quote_with_ocerp_uses_updated_tenant_pricing_settings(
    admin_client: AsyncClient,
) -> None:
    contact = await _create_contact(
        admin_client, admin_client.headers["X-Tenant-ID"], "Pricing Customer"
    )

    def _mock_generate_boq(request: Any) -> BoQGenerateResponse:
        tenant_settings = request.tenant_settings or {}
        hourly = Decimal(str(tenant_settings.get("hourly_labour_rate", "45")))
        markup = Decimal(str(tenant_settings.get("markup_percentage", "0")))
        minimum_charge = Decimal(str(tenant_settings.get("minimum_charge", "0")))

        material_base = Decimal("100.00")
        material_total = (material_base * (Decimal("1") + markup / Decimal("100"))).quantize(
            Decimal("0.01")
        )
        subtotal = (material_total + hourly).quantize(Decimal("0.01"))
        if minimum_charge > subtotal:
            subtotal = minimum_charge
        vat_amount = (subtotal * Decimal("0.20")).quantize(Decimal("0.01"))
        total = (subtotal + vat_amount).quantize(Decimal("0.01"))

        return BoQGenerateResponse(
            line_items=[
                BoQLineItem(
                    code="TEST-LINE",
                    description="Tenant priced line",
                    unit="each",
                    quantity=Decimal("1"),
                    labour_hours=Decimal("1.00"),
                    labour_rate=hourly,
                    labour_total=hourly,
                    material_cost=material_total,
                    material_total=material_total,
                    plant_cost=Decimal("0.00"),
                    plant_total=Decimal("0.00"),
                    unit_price=subtotal,
                    total=subtotal,
                )
            ],
            subtotal=subtotal,
            vat_amount=vat_amount,
            total=total,
            confidence=Decimal("1.0"),
            notes="Pricing derived from tenant settings",
            standard="nrm1",
        )

    with patch(
        "app.clients.ocerp.OCERPClient.generate_boq", new=AsyncMock(side_effect=_mock_generate_boq)
    ):
        before = await admin_client.post(
            "/quotes/generate",
            headers={"X-Tenant-ID": admin_client.headers["X-Tenant-ID"]},
            json={
                "contact_id": contact["id"],
                "description": "Generate pricing before settings update",
                "use_ocerp": True,
            },
        )
        assert before.status_code == 201

        update = await admin_client.patch(
            "/tenants/me",
            json={
                "settings": {
                    "hourly_labour_rate": "80.00",
                    "markup_percentage": "25.00",
                    "minimum_charge": "300.00",
                }
            },
        )
        assert update.status_code == 200

        after = await admin_client.post(
            "/quotes/generate",
            headers={"X-Tenant-ID": admin_client.headers["X-Tenant-ID"]},
            json={
                "contact_id": contact["id"],
                "description": "Generate pricing after settings update",
                "use_ocerp": True,
            },
        )
        assert after.status_code == 201

    before_total = Decimal(before.json()["total"])
    after_total = Decimal(after.json()["total"])
    assert after_total > before_total
    assert before_total == Decimal("174.00")
    assert after_total == Decimal("360.00")


@pytest.mark.skip(reason="OCERP/BoQ is parked for the mobile-pivot MVP")
@pytest.mark.asyncio
async def test_regenerate_boq_keeps_customer_total_locked_while_boq_reprices(
    admin_client: AsyncClient,
) -> None:
    contact = await _create_contact(
        admin_client,
        admin_client.headers["X-Tenant-ID"],
        "Reprice Customer",
    )

    initial_boq = BoQGenerateResponse(
        line_items=[
            BoQLineItem(
                code="TEST-LINE",
                description="Initial priced line",
                unit="each",
                quantity=Decimal("1"),
                labour_hours=Decimal("1.00"),
                labour_rate=Decimal("20.00"),
                labour_total=Decimal("20.00"),
                material_cost=Decimal("80.00"),
                material_total=Decimal("80.00"),
                plant_cost=Decimal("0.00"),
                plant_total=Decimal("0.00"),
                unit_price=Decimal("100.00"),
                total=Decimal("100.00"),
            )
        ],
        subtotal=Decimal("100.00"),
        vat_amount=Decimal("20.00"),
        total=Decimal("120.00"),
        confidence=Decimal("1.0"),
        notes="Initial pricing",
        standard="nrm1",
    )
    repriced_boq = BoQGenerateResponse(
        line_items=[
            BoQLineItem(
                code="TEST-LINE",
                description="Repriced line",
                unit="each",
                quantity=Decimal("1"),
                labour_hours=Decimal("1.00"),
                labour_rate=Decimal("15.00"),
                labour_total=Decimal("15.00"),
                material_cost=Decimal("55.00"),
                material_total=Decimal("55.00"),
                plant_cost=Decimal("0.00"),
                plant_total=Decimal("0.00"),
                unit_price=Decimal("70.00"),
                total=Decimal("70.00"),
            )
        ],
        subtotal=Decimal("70.00"),
        vat_amount=Decimal("14.00"),
        total=Decimal("84.00"),
        confidence=Decimal("1.0"),
        notes="Repriced lower",
        standard="nrm1",
    )

    with patch(
        "app.clients.ocerp.OCERPClient.generate_boq",
        new=AsyncMock(side_effect=[initial_boq, repriced_boq]),
    ):
        created = await admin_client.post(
            "/quotes/generate",
            headers={"X-Tenant-ID": admin_client.headers["X-Tenant-ID"]},
            json={
                "contact_id": contact["id"],
                "description": "Generate quote for reprice test",
                "use_ocerp": True,
            },
        )
        assert created.status_code == 201
        quote_id = created.json()["id"]

        regenerated = await admin_client.post(
            f"/quotes/{quote_id}/boq/regenerate",
            headers={"X-Tenant-ID": admin_client.headers["X-Tenant-ID"]},
        )
        assert regenerated.status_code == 201

    # Internal BoQ is refreshed to the lower repriced amount.
    regenerated_boq = regenerated.json()
    assert Decimal(regenerated_boq["total"]) == Decimal("84.00")
    assert any("customer quote total" in warning.lower() for warning in regenerated_boq["warnings"])

    # Customer-facing quote remains locked to the original commercial total.
    quote_after = await admin_client.get(
        f"/quotes/{quote_id}",
        headers={"X-Tenant-ID": admin_client.headers["X-Tenant-ID"]},
    )
    assert quote_after.status_code == 200
    assert Decimal(quote_after.json()["total"]) == Decimal("120.00")


@pytest.mark.skip(reason="OCERP/BoQ is parked for the mobile-pivot MVP")
@pytest.mark.asyncio
async def test_manual_boq_edit_updates_boq_total_but_keeps_customer_quote_locked(
    admin_client: AsyncClient,
) -> None:
    contact = await _create_contact(
        admin_client,
        admin_client.headers["X-Tenant-ID"],
        "Manual Edit Customer",
    )

    initial_boq = BoQGenerateResponse(
        line_items=[
            BoQLineItem(
                code="EDIT-LINE",
                description="Editable line",
                unit="each",
                quantity=Decimal("1"),
                labour_hours=Decimal("1.00"),
                labour_rate=Decimal("20.00"),
                labour_total=Decimal("20.00"),
                material_cost=Decimal("80.00"),
                material_total=Decimal("80.00"),
                plant_cost=Decimal("0.00"),
                plant_total=Decimal("0.00"),
                unit_price=Decimal("100.00"),
                total=Decimal("100.00"),
            )
        ],
        subtotal=Decimal("100.00"),
        vat_amount=Decimal("20.00"),
        total=Decimal("120.00"),
        confidence=Decimal("1.0"),
        notes="Initial pricing",
        standard="nrm1",
    )

    with patch(
        "app.clients.ocerp.OCERPClient.generate_boq",
        new=AsyncMock(return_value=initial_boq),
    ):
        created = await admin_client.post(
            "/quotes/generate",
            headers={"X-Tenant-ID": admin_client.headers["X-Tenant-ID"]},
            json={
                "contact_id": contact["id"],
                "description": "Generate quote for manual BoQ edit test",
                "use_ocerp": True,
            },
        )
        assert created.status_code == 201
        quote_id = created.json()["id"]

    updated_boq = await admin_client.patch(
        f"/quotes/{quote_id}/boq",
        headers={"X-Tenant-ID": admin_client.headers["X-Tenant-ID"]},
        json={
            "notes": "Adjusted after review",
            "line_items": [
                {
                    "code": "EDIT-LINE",
                    "description": "Editable line",
                    "unit": "each",
                    "quantity": "1",
                    "labour_hours": "1.00",
                    "labour_rate": "10.00",
                    "labour_total": "10.00",
                    "material_cost": "50.00",
                    "material_total": "50.00",
                    "plant_cost": "0.00",
                    "plant_total": "0.00",
                    "notes": "edited",
                }
            ],
        },
    )
    assert updated_boq.status_code == 200
    assert Decimal(updated_boq.json()["total"]) == Decimal("72.00")

    quote_after = await admin_client.get(
        f"/quotes/{quote_id}",
        headers={"X-Tenant-ID": admin_client.headers["X-Tenant-ID"]},
    )
    assert quote_after.status_code == 200
    assert Decimal(quote_after.json()["total"]) == Decimal("120.00")
