"""Integration tests for the public, no-auth AI quote demo endpoints."""

from __future__ import annotations

from contextlib import contextmanager
from decimal import Decimal
from http.cookies import SimpleCookie
from typing import TYPE_CHECKING, Any

import pytest
from app.config import settings
from app.limiter import limiter
from app.models import DemoQuoteEvent
from sqlalchemy import select

if TYPE_CHECKING:
    from collections.abc import AsyncIterator, Iterator

    from httpx import AsyncClient
    from sqlalchemy.ext.asyncio import AsyncSession

DESCRIPTION = "I need two extra double sockets installed in the kitchen walls"

_DEMO_USED_COOKIE = "mtp_demo_used"
_DEMO_USED_MESSAGE = "You've already tried the AI demo — download the app for unlimited quotes."
_DEMO_USED_KEY_PREFIX = "mtp:demo:used:"
_ALLOWED_ORIGIN = "http://localhost:3000"

# Labour priced AT the demo tenant rate (£65/hr) so validation's labour snap
# (drift > 20%) does not rewrite it; material is guide-priced (no catalogue).
_GENERATED = {
    "line_items": [
        {
            "description": "Install double socket (labour per point)",
            "kind": "labour",
            "unit": "hour",
            "quantity": 4,
            "unit_price": 65.00,
        },
        {
            "description": "Double socket faceplate and back box",
            "kind": "material",
            "unit": "each",
            "quantity": 2,
            "unit_price": 18.50,
        },
    ],
    "assumptions": ["Assumed standard back boxes already in place"],
    "notes": "Generated by AI",
}

_RETRIEVED: list[dict[str, Any]] = []


@contextmanager
def _mock_llm(generated: dict[str, Any] | None = None, retrieval_status: str = "no_index") -> Any:
    from unittest.mock import AsyncMock, patch

    generate_mock = AsyncMock(return_value=generated if generated is not None else _GENERATED)
    with (
        patch(
            "app.routers.demo.search_cost_items_with_status",
            new=AsyncMock(return_value=(_RETRIEVED, retrieval_status)),
        ),
        patch("app.routers.demo.generate_quote_from_prompt", new=generate_mock),
    ):
        yield generate_mock


async def _all_events(db: AsyncSession) -> list[DemoQuoteEvent]:
    rows = await db.execute(select(DemoQuoteEvent))
    return list(rows.scalars().all())


async def _clean_demo_used_flags() -> None:
    """Delete every demo one-shot flag so tests don't leak fingerprints."""
    from app.redis_client import get_redis

    redis = get_redis()
    keys = [key async for key in redis.scan_iter(match=f"{_DEMO_USED_KEY_PREFIX}*")]
    if keys:
        await redis.delete(*keys)


@pytest.fixture(autouse=True)
async def _demo_used_flags_cleanup() -> AsyncIterator[None]:
    """The demo gate keys on IP+UA+Accept-Language, which is identical for
    every test client, so flags must be cleared around each test."""
    await _clean_demo_used_flags()
    try:
        yield
    finally:
        await _clean_demo_used_flags()


def _used_cookie_morsel(response: Any) -> Any:
    set_cookie = response.headers.get_list("set-cookie")[0]
    jar = SimpleCookie()
    jar.load(set_cookie)
    return jar[_DEMO_USED_COOKIE]


@pytest.mark.asyncio
async def test_demo_generate_returns_line_items_and_ai_metadata(
    client: AsyncClient, db: AsyncSession
) -> None:
    with _mock_llm():
        response = await client.post(
            "/demo/quotes/generate",
            json={
                "description": DESCRIPTION,
                "property_type": "detached_house",
                "utm_source": "landing",
                "utm_medium": "cta",
                "utm_campaign": "beta",
            },
            headers={"user-agent": "pytest-demo/1.0", "referer": "https://example.com/"},
        )

    assert response.status_code == 200, response.text
    body = response.json()
    assert len(body["line_items"]) == 2
    labour = body["line_items"][0]
    assert labour["description"] == "Install double socket (labour per point)"
    assert labour["ai_generated"] is True
    assert Decimal(labour["total"]) == Decimal("260.00")
    # VAT-registered demo business: 20% on the 297.00 subtotal.
    assert Decimal(body["subtotal"]) == Decimal("297.00")
    assert Decimal(body["vat_rate"]) == Decimal("0.20")
    assert Decimal(body["vat_amount"]) == Decimal("59.40")
    assert Decimal(body["total"]) == Decimal("356.40")
    # AI metadata mirrors QuoteRead's ai_* / retrieval_status fields.
    assert body["ai"]["confidence"] is not None
    assert body["ai"]["assumptions"] == ["Assumed standard back boxes already in place"]
    assert body["ai"]["notes"] == "Generated by AI"
    assert body["ai"]["warnings"] == []
    assert body["retrieval_status"] == "no_index"
    assert body["generation_seconds"] >= 0


@pytest.mark.asyncio
async def test_demo_generate_records_event_without_persisting_content(
    client: AsyncClient, db: AsyncSession
) -> None:
    with _mock_llm():
        response = await client.post(
            "/demo/quotes/generate",
            json={
                "description": DESCRIPTION,
                "utm_source": "landing",
            },
            headers={"user-agent": "pytest-demo/1.0"},
        )
    assert response.status_code == 200, response.text

    events = await _all_events(db)
    assert len(events) == 1
    event = events[0]
    assert event.ip_hash
    assert len(event.ip_hash) == 64
    assert event.utm_source == "landing"
    assert event.user_agent == "pytest-demo/1.0"
    assert event.generation_seconds is not None

    # Nothing about the job description or the generated quote may be durable:
    # inspect every column of every row for any fragment of the content.
    sentinel = "extra double sockets installed in the kitchen"
    for row in events:
        for column in DemoQuoteEvent.__table__.columns:
            value = getattr(row, column.name)
            assert sentinel not in str(value), f"description leaked into {column.name}"


@pytest.mark.asyncio
async def test_demo_generate_uses_fallback_lines_when_llm_returns_nothing(
    client: AsyncClient, db: AsyncSession
) -> None:
    with _mock_llm(generated={"line_items": [], "notes": ""}):
        response = await client.post(
            "/demo/quotes/generate",
            json={"description": "Consumer unit replacement needed for a 3 bed house"},
        )
    assert response.status_code == 200, response.text
    body = response.json()
    assert len(body["line_items"]) > 0
    assert all(li["ai_generated"] for li in body["line_items"])
    assert any("Consumer unit" in li["description"] for li in body["line_items"])
    assert any("guide-price" in w.lower() for w in body["ai"]["warnings"])


@pytest.mark.asyncio
async def test_demo_generate_routes_to_openai_fast_model_when_key_configured(
    client: AsyncClient,
    db: AsyncSession,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """With an OpenAI key, the demo overrides the slow production pipeline and
    calls the LLM with the fast demo model + OpenAI key and no api_base."""
    monkeypatch.setattr(settings, "openai_api_key", "sk-test-openai")
    monkeypatch.setattr(settings, "demo_llm_model", "gpt-4o-mini")
    with _mock_llm() as generate_mock:
        response = await client.post(
            "/demo/quotes/generate",
            json={"description": DESCRIPTION},
            headers={"user-agent": "pytest-demo-llm-fast/1.0"},
        )
    assert response.status_code == 200, response.text
    assert generate_mock.call_count == 1
    _, kwargs = generate_mock.call_args
    assert kwargs["model"] == "gpt-4o-mini"
    assert kwargs["api_key"] == "sk-test-openai"
    # Empty base suppresses a production Kimi base so OpenAI defaults apply.
    assert kwargs["api_base"] == ""


@pytest.mark.asyncio
async def test_demo_generate_uses_default_pipeline_without_openai_key(
    client: AsyncClient,
    db: AsyncSession,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Without an OpenAI key the demo passes no overrides — the production
    pipeline config (LLM_MODEL/LLM_API_BASE/key) is used unchanged."""
    monkeypatch.setattr(settings, "openai_api_key", "")
    with _mock_llm() as generate_mock:
        response = await client.post(
            "/demo/quotes/generate",
            json={"description": DESCRIPTION},
            headers={"user-agent": "pytest-demo-llm-default/1.0"},
        )
    assert response.status_code == 200, response.text
    _, kwargs = generate_mock.call_args
    assert "model" not in kwargs
    assert "api_key" not in kwargs
    assert "api_base" not in kwargs


@pytest.mark.asyncio
async def test_demo_refine_also_routes_to_openai_fast_model_when_key_configured(
    client: AsyncClient,
    db: AsyncSession,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """The refine path must hit the same fast demo model as generate."""
    monkeypatch.setattr(settings, "openai_api_key", "sk-test-openai")
    monkeypatch.setattr(settings, "demo_llm_model", "gpt-4o-mini")
    with _mock_llm() as generate_mock:
        response = await client.post(
            "/demo/quotes/refine",
            json={
                "description": DESCRIPTION,
                "instructions": "Adjust the labour to two hours please",
                "line_items": [
                    {
                        "description": "Install double socket (labour per point)",
                        "quantity": "2",
                        "unit": "hour",
                        "unit_price": "65.00",
                        "ai_generated": True,
                    }
                ],
            },
        )
    assert response.status_code == 200, response.text
    _, kwargs = generate_mock.call_args
    assert kwargs["model"] == "gpt-4o-mini"
    assert kwargs["api_key"] == "sk-test-openai"
    assert kwargs["api_base"] == ""


@pytest.mark.asyncio
async def test_demo_generate_returns_502_when_llm_unavailable(client: AsyncClient) -> None:
    from unittest.mock import AsyncMock, patch

    with patch(
        "app.routers.demo.search_cost_items_with_status",
        new=AsyncMock(side_effect=RuntimeError("LLM API key is not configured")),
    ):
        response = await client.post(
            "/demo/quotes/generate",
            json={"description": DESCRIPTION},
        )
    assert response.status_code == 502
    assert response.json() == {"detail": "The AI is busy right now — try again in a moment."}


@pytest.mark.asyncio
async def test_demo_generate_second_attempt_with_cookie_gets_429(
    client: AsyncClient, db: AsyncSession
) -> None:
    """A visitor carrying mtp_demo_used=1 is rejected before any LLM spend."""
    with _mock_llm():
        first = await client.post(
            "/demo/quotes/generate",
            json={"description": DESCRIPTION},
            headers={"user-agent": "pytest-demo-gate/1.0"},
        )
    assert first.status_code == 200, first.text

    with _mock_llm() as generate_mock:
        second = await client.post(
            "/demo/quotes/generate",
            json={"description": DESCRIPTION},
            headers={"user-agent": "pytest-demo-gate/1.0"},
            cookies={_DEMO_USED_COOKIE: "1"},
        )
    assert second.status_code == 429
    assert second.json() == {"detail": _DEMO_USED_MESSAGE}
    # The gate tripped before the LLM was called again.
    generate_mock.assert_not_called()


@pytest.mark.asyncio
async def test_demo_generate_second_attempt_without_cookie_gets_429_via_redis(
    client: AsyncClient, db: AsyncSession
) -> None:
    """No cookie, but the Redis fingerprint flag from attempt one trips the gate."""
    headers = {"user-agent": "pytest-demo-redis/1.0", "accept-language": "en-GB"}
    with _mock_llm():
        first = await client.post(
            "/demo/quotes/generate",
            json={"description": DESCRIPTION},
            headers=headers,
        )
    assert first.status_code == 200, first.text

    with _mock_llm():
        second = await client.post(
            "/demo/quotes/generate",
            json={"description": DESCRIPTION},
            headers=headers,
        )
    assert second.status_code == 429
    assert second.json() == {"detail": _DEMO_USED_MESSAGE}

    # The fingerprint flag was stored with ~30-day TTL.
    from app.redis_client import get_redis

    redis = get_redis()
    keys = [k async for k in redis.scan_iter(match=f"{_DEMO_USED_KEY_PREFIX}*")]
    assert len(keys) == 1
    ttl = await redis.ttl(keys[0])
    assert 29 * 24 * 60 * 60 < ttl <= 30 * 24 * 60 * 60


@pytest.mark.asyncio
async def test_demo_refine_still_works_after_generate_gate_trips(
    client: AsyncClient, db: AsyncSession
) -> None:
    """Refine is part of the same quote: the one-shot generate gate must not
    block it, even when the visitor carries the mtp_demo_used cookie."""
    with _mock_llm():
        generate = await client.post(
            "/demo/quotes/generate",
            json={"description": DESCRIPTION},
        )
    assert generate.status_code == 200, generate.text

    blocked = await client.post(
        "/demo/quotes/generate",
        json={"description": DESCRIPTION},
        cookies={_DEMO_USED_COOKIE: "1"},
    )
    assert blocked.status_code == 429

    with _mock_llm():
        refine = await client.post(
            "/demo/quotes/refine",
            json={
                "description": DESCRIPTION,
                "instructions": "Adjust the labour to two hours please",
                "line_items": [
                    {
                        "description": "Install double socket (labour per point)",
                        "quantity": "2",
                        "unit": "hour",
                        "unit_price": "65.00",
                        "ai_generated": True,
                    }
                ],
            },
            cookies={_DEMO_USED_COOKIE: "1"},
        )
    assert refine.status_code == 200, refine.text


@pytest.mark.asyncio
async def test_demo_generate_429_carries_cors_credentials_header(
    client: AsyncClient, db: AsyncSession
) -> None:
    """Credentialed cross-site callers must see Access-Control-Allow-Credentials
    on the 429 too, or the browser hides the response from the landing page."""
    with _mock_llm():
        first = await client.post(
            "/demo/quotes/generate",
            json={"description": DESCRIPTION},
        )
    assert first.status_code == 200, first.text

    second = await client.post(
        "/demo/quotes/generate",
        json={"description": DESCRIPTION},
        cookies={_DEMO_USED_COOKIE: "1"},
        headers={"Origin": _ALLOWED_ORIGIN},
    )
    assert second.status_code == 429
    assert second.headers.get("access-control-allow-credentials") == "true"
    assert second.headers.get("access-control-allow-origin") == _ALLOWED_ORIGIN


@pytest.mark.asyncio
async def test_demo_generate_success_sets_used_cookie_with_cross_site_attributes(
    client: AsyncClient, db: AsyncSession
) -> None:
    """The landing is cross-site (www → *.up.railway.app): SameSite=None +
    Secure is required for the browser to send the cookie on credentialed XHR."""
    with _mock_llm():
        response = await client.post(
            "/demo/quotes/generate",
            json={"description": DESCRIPTION},
        )
    assert response.status_code == 200, response.text

    morsel = _used_cookie_morsel(response)
    assert morsel.value == "1"
    assert morsel["httponly"] is True
    assert morsel["samesite"].lower() == "none"
    assert morsel["secure"] is True
    assert morsel["path"] == "/"
    assert morsel["max-age"] == str(180 * 24 * 60 * 60)


@pytest.mark.asyncio
async def test_demo_generate_allows_when_redis_unavailable(
    client: AsyncClient,
    db: AsyncSession,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A down Redis must not break the demo — the gate degrades to 'allow'."""

    class _BoomRedis:
        async def get(self, key: str) -> None:
            raise ConnectionError("redis is down")

        async def set(self, *args: Any, **kwargs: Any) -> None:
            raise ConnectionError("redis is down")

    monkeypatch.setattr("app.routers.demo.get_redis", lambda: _BoomRedis())
    with _mock_llm():
        response = await client.post(
            "/demo/quotes/generate",
            json={"description": DESCRIPTION},
        )
    assert response.status_code == 200, response.text
    # The cookie is still set — it alone will gate the next attempt.
    assert _used_cookie_morsel(response).value == "1"


@pytest.mark.asyncio
async def test_demo_refine_preserves_manual_lines_and_replaces_ai_lines(
    client: AsyncClient, db: AsyncSession
) -> None:
    manual_line = {
        "description": "My own priced faceplate",
        "quantity": "1",
        "unit": "ea",
        "unit_price": "150.00",
        "ai_generated": False,
    }
    ai_line = {
        "description": "Install double socket (labour per point)",
        "quantity": "2",
        "unit": "hour",
        "unit_price": "65.00",
        "ai_generated": True,
    }
    refined = {
        "line_items": [
            {
                "description": "Install double socket incl. chasing",
                "kind": "labour",
                "unit": "hour",
                "quantity": 3,
                "unit_price": 65.00,
            }
        ],
        "notes": "Refined per instructions",
    }
    with _mock_llm(generated=refined):
        response = await client.post(
            "/demo/quotes/refine",
            json={
                "description": DESCRIPTION,
                "instructions": "Include chasing the walls for the cable runs",
                "line_items": [manual_line, ai_line],
            },
        )
    assert response.status_code == 200, response.text
    body = response.json()
    by_description = {li["description"]: li for li in body["line_items"]}

    # Manual line survives untouched; the AI line was regenerated.
    assert by_description["My own priced faceplate"]["ai_generated"] is False
    assert Decimal(by_description["My own priced faceplate"]["unit_price"]) == Decimal("150.00")
    assert "Install double socket (labour per point)" not in by_description
    refined_line = by_description["Install double socket incl. chasing"]
    assert refined_line["ai_generated"] is True
    assert refined_line["quantity"] == "3"

    # Totals recalculated: (150 + 195) ex-VAT, plus 20% VAT.
    assert Decimal(body["subtotal"]) == Decimal("345.00")
    assert Decimal(body["total"]) == Decimal("414.00")
    assert body["ai"]["notes"] == "Refined per instructions"


@pytest.mark.asyncio
async def test_demo_generate_rejects_short_description(client: AsyncClient) -> None:
    response = await client.post(
        "/demo/quotes/generate",
        json={"description": "fix socket"},
    )
    assert response.status_code == 422


@pytest.mark.asyncio
async def test_demo_refine_rejects_short_instructions(client: AsyncClient) -> None:
    response = await client.post(
        "/demo/quotes/refine",
        json={
            "description": DESCRIPTION,
            "instructions": "ok",
            "line_items": [
                {
                    "description": "Line",
                    "quantity": "1",
                    "unit": "ea",
                    "unit_price": "10.00",
                    "ai_generated": True,
                }
            ],
        },
    )
    assert response.status_code == 422


@pytest.fixture()
def _enable_rate_limiter() -> Iterator[None]:
    """Re-enable the limiter for these tests and clear its in-memory buckets."""
    previous = limiter.enabled
    limiter.enabled = True
    limiter.reset()
    try:
        yield
    finally:
        limiter.reset()
        limiter.enabled = previous


@pytest.mark.asyncio
async def test_demo_generate_rate_limit_kicks_in_after_five(
    client: AsyncClient,
    db: AsyncSession,
    _enable_rate_limiter: None,
) -> None:
    """The 6th rapid demo generation from one IP must be rejected with 429."""
    payload = {"description": DESCRIPTION}
    for i in range(5):
        with _mock_llm():
            response = await client.post(
                "/demo/quotes/generate",
                json=payload,
                # A fresh fingerprint per request: this test exercises the
                # per-IP limiter, not the one-generate-per-visitor gate.
                headers={"user-agent": f"pytest-rate-limit/{i}"},
            )
        assert response.status_code == 200, response.text
        client.cookies.clear()

    sixth = await client.post(
        "/demo/quotes/generate",
        json=payload,
        headers={"user-agent": "pytest-rate-limit/6"},
    )
    assert sixth.status_code == 429


@pytest.mark.asyncio
async def test_demo_refine_rate_limit_kicks_in_after_ten(
    client: AsyncClient,
    db: AsyncSession,
    _enable_rate_limiter: None,
) -> None:
    """The 11th rapid demo refinement from one IP must be rejected with 429."""
    line = {
        "description": "Line",
        "quantity": "1",
        "unit": "ea",
        "unit_price": "10.00",
        "ai_generated": True,
    }
    payload = {
        "description": DESCRIPTION,
        "instructions": "Adjust the labour to two hours please",
        "line_items": [line],
    }
    for _ in range(10):
        with _mock_llm():
            response = await client.post("/demo/quotes/refine", json=payload)
        assert response.status_code == 200, response.text

    eleventh = await client.post("/demo/quotes/refine", json=payload)
    assert eleventh.status_code == 429


@pytest.mark.asyncio
async def test_demo_generate_event_survives_storage_failure(
    client: AsyncClient,
    db: AsyncSession,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """If the analytics insert fails, the demo response still succeeds."""

    async def _exploding_commit() -> None:
        raise RuntimeError("database is read-only")

    monkeypatch.setattr(db, "commit", _exploding_commit)
    with _mock_llm():
        response = await client.post(
            "/demo/quotes/generate",
            json={"description": DESCRIPTION},
        )
    assert response.status_code == 200, response.text
    # No event row was written, and the failed insert was rolled back.
    assert await _all_events(db) == []


def test_demo_settings_match_pipeline_keys() -> None:
    """The demo defaults must contain every key the RAG pipeline reads."""
    from app.routers.demo import DEMO_TENANT_SETTINGS

    assert settings.auth_secret_key  # salt source for ip_hash is configured
    for key in ("minimum_charge", "markup_percent", "hourly_labour_rate"):
        assert key in DEMO_TENANT_SETTINGS
