"""PDF generation helpers for operational documents."""

from datetime import datetime
from decimal import Decimal
from typing import Any

from fpdf import FPDF

from app.models import Quote


def _safe_text(text: Any) -> str:
    """Return a string safe for the PDF's built-in font encoding."""
    if text is None:
        return ""
    return str(text).encode("latin-1", "replace").decode("latin-1")


def _format_money(amount: Decimal) -> str:
    return f"GBP {amount:.2f}"


class QuotePDF(FPDF):
    def header(self) -> None:
        self.set_font("Helvetica", "B", 16)
        self.cell(0, 10, _safe_text(self.tenant_name), ln=True, align="L")  # type: ignore[attr-defined, arg-type]
        self.set_font("Helvetica", "", 10)
        self.cell(0, 6, "Quote", ln=True, align="L")  # type: ignore[arg-type]
        self.ln(4)

    def footer(self) -> None:
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by My Trade Portal", align="C")


def generate_quote_pdf(quote: Quote, tenant_name: str) -> bytes:
    """Generate a branded PDF for a quote and return the bytes."""
    pdf = QuotePDF()
    pdf.tenant_name = tenant_name  # type: ignore[attr-defined]
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Quote metadata
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, f"Quote ref: {quote.id}", ln=True)  # type: ignore[arg-type]
    pdf.cell(0, 6, f"Date: {datetime.utcnow().strftime('%d %B %Y')}", ln=True)  # type: ignore[arg-type]
    if quote.valid_until:
        pdf.cell(
            0,
            6,
            f"Valid until: {quote.valid_until.strftime('%d %B %Y')}",
            ln=True,  # type: ignore[arg-type]
        )
    pdf.ln(6)

    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, _safe_text(quote.title), ln=True)  # type: ignore[arg-type]
    if quote.description:
        pdf.set_font("Helvetica", "", 10)
        pdf.multi_cell(0, 6, _safe_text(quote.description))
        pdf.ln(4)

    # Line items table
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_fill_color(230, 230, 230)
    pdf.cell(100, 8, "Description", border=1, fill=True)
    pdf.cell(25, 8, "Qty", border=1, align="C", fill=True)
    pdf.cell(30, 8, "Unit", border=1, align="R", fill=True)
    pdf.cell(35, 8, "Total", border=1, align="R", fill=True)
    pdf.ln()

    pdf.set_font("Helvetica", "", 10)
    for item in quote.line_items:
        pdf.cell(100, 8, _safe_text(item.description), border=1)
        pdf.cell(25, 8, _safe_text(item.quantity), border=1, align="C")
        pdf.cell(30, 8, _format_money(item.unit_price), border=1, align="R")
        pdf.cell(35, 8, _format_money(item.total), border=1, align="R")
        pdf.ln()

    # Totals
    pdf.ln(4)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(155, 8, "Subtotal", align="R")
    pdf.cell(35, 8, _format_money(quote.subtotal), align="R")
    pdf.ln()
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(155, 8, f"VAT ({quote.vat_rate * 100:.0f}%)", align="R")
    pdf.cell(35, 8, _format_money(quote.vat_amount), align="R")
    pdf.ln()
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(155, 10, "Total", align="R")
    pdf.cell(35, 10, _format_money(quote.total), align="R")
    pdf.ln()

    output = pdf.output(dest="S")  # type: ignore[call-overload]
    if isinstance(output, str):
        return output.encode("latin-1")
    return bytes(output)
