#!/usr/bin/env bash
set -euo pipefail

# Generate a local `.env.prod-replica` file from the production Railway
# environment so the local Docker stack runs with the same secrets and
# external service configuration as production.

cd "$(dirname "$0")/.."

ENV_FILE=".env.prod-replica"
RAILWAY_ENV="production"

command -v railway >/dev/null || {
  echo "railway CLI is required: brew install railway" >&2
  exit 1
}

# Helper: fetch a single env var for a service. Returns empty string on
# failure so the script does not abort on missing optional vars.
fetch_var() {
  local service="$1"
  local var="$2"
  railway run --service "$service" --environment "$RAILWAY_ENV" \
    sh -c "printf '%s' \"\${$var:-}\"" 2>/dev/null || true
}

# Helper: write a var only when it is non-empty.
write_var() {
  local name="$1"
  local value="$2"
  if [ -n "$value" ]; then
    printf '%s=%s\n' "$name" "$value"
  fi
}

echo "Fetching production variables from Railway (environment: ${RAILWAY_ENV})..."

OPENAI_API_KEY=$(fetch_var api OPENAI_API_KEY)
EMBEDDING_MODEL=$(fetch_var api EMBEDDING_MODEL)
LLM_MODEL=$(fetch_var api LLM_MODEL)
LLM_TIMEOUT_SECONDS=$(fetch_var api LLM_TIMEOUT_SECONDS)
AUTH_SECRET_KEY=$(fetch_var api AUTH_SECRET_KEY)
SETUP_TOKEN=$(fetch_var api SETUP_TOKEN)
APP_ROLE_NAME=$(fetch_var api APP_ROLE_NAME)
APP_ROLE_PASSWORD=$(fetch_var api APP_ROLE_PASSWORD)
RAILWAY_TOKEN=$(fetch_var api RAILWAY_TOKEN)
RAILWAY_PROJECT_ID=$(fetch_var api RAILWAY_PROJECT_ID)
PADDLE_API_KEY=$(fetch_var api PADDLE_API_KEY)
PADDLE_WEBHOOK_SECRET=$(fetch_var api PADDLE_WEBHOOK_SECRET)
NEW_RELIC_LICENSE_KEY=$(fetch_var api NEW_RELIC_LICENSE_KEY)

ADMIN_SECRET_KEY=$(fetch_var admin SECRET_KEY)
DJANGO_SUPERUSER_USERNAME=$(fetch_var admin DJANGO_SUPERUSER_USERNAME)
DJANGO_SUPERUSER_EMAIL=$(fetch_var admin DJANGO_SUPERUSER_EMAIL)
DJANGO_SUPERUSER_PASSWORD=$(fetch_var admin DJANGO_SUPERUSER_PASSWORD)

APIFY_API_TOKEN=$(fetch_var data-pipeline APIFY_API_TOKEN)

cat > "$ENV_FILE" <<EOF
# Generated by scripts/generate-prod-replica-env.sh — DO NOT COMMIT
# Local prod-replica overrides: infrastructure points to local containers,
# secrets/external services match Railway production.

# ---------------------------------------------------------------------
# Local infrastructure (Docker Compose)
# ---------------------------------------------------------------------
ENVIRONMENT=production
LOG_LEVEL=INFO

DATABASE_URL=postgresql+asyncpg://mtp:mtp@postgres:5432/mtp
REDIS_URL=redis://redis:6379/0
QDRANT_URL=http://qdrant:6333
QDRANT_COLLECTION_NAME=cost_items
QDRANT_KNOWLEDGE_COLLECTION_NAME=quoting_knowledge

MINIO_ENDPOINT=minio:9000
MINIO_USE_SSL=false
MINIO_ACCESS_KEY=minioadmin
MINIO_SECRET_KEY=minioadmin
MINIO_BUCKET=mtp-uploads

# Django uses plain postgresql:// (psycopg2), not the async driver.
ADMIN_DATABASE_URL=postgresql://mtp:mtp@postgres:5432/mtp
ADMIN_DEBUG=False
ADMIN_ALLOWED_HOSTS=localhost,127.0.0.1,admin
ADMIN_CSRF_TRUSTED_ORIGINS=http://localhost:8001

# Internal service URLs inside the compose network.
OCERP_URL=http://ocerp:8000
SMTP_HOST=mailpit
SMTP_PORT=1025

# ---------------------------------------------------------------------
# Production secrets / external services (fetched from Railway)
# ---------------------------------------------------------------------
$(write_var OPENAI_API_KEY "$OPENAI_API_KEY")
EMBEDDING_MODEL=${EMBEDDING_MODEL:-text-embedding-3-small}
LLM_MODEL=${LLM_MODEL:-gpt-4o-mini}
LLM_TIMEOUT_SECONDS=${LLM_TIMEOUT_SECONDS:-120}

$(write_var AUTH_SECRET_KEY "$AUTH_SECRET_KEY")
$(write_var SETUP_TOKEN "$SETUP_TOKEN")

$(write_var APP_ROLE_NAME "$APP_ROLE_NAME")
$(write_var APP_ROLE_PASSWORD "$APP_ROLE_PASSWORD")

$(write_var RAILWAY_TOKEN "$RAILWAY_TOKEN")
$(write_var RAILWAY_PROJECT_ID "$RAILWAY_PROJECT_ID")

$(write_var PADDLE_API_KEY "$PADDLE_API_KEY")
$(write_var PADDLE_WEBHOOK_SECRET "$PADDLE_WEBHOOK_SECRET")
PADDLE_SANDBOX=true

$(write_var NEW_RELIC_LICENSE_KEY "$NEW_RELIC_LICENSE_KEY")
NEW_RELIC_APP_NAME=mytradeportal-api

# Admin bootstrap (production superuser for tenant onboarding)
$(write_var ADMIN_SECRET_KEY "$ADMIN_SECRET_KEY")
$(write_var DJANGO_SUPERUSER_USERNAME "$DJANGO_SUPERUSER_USERNAME")
$(write_var DJANGO_SUPERUSER_EMAIL "$DJANGO_SUPERUSER_EMAIL")
$(write_var DJANGO_SUPERUSER_PASSWORD "$DJANGO_SUPERUSER_PASSWORD")

# Data pipeline
$(write_var APIFY_API_TOKEN "$APIFY_API_TOKEN")
PIPELINE_DEMO_MODE=false
SCREWFIX_START_URL=https://www.screwfix.com/c/electrical-lighting/cat840780
SCREWFIX_MAX_ITEMS=10000
SCREWFIX_SCRAPE_DETAILS=false
SCREWFIX_MAX_TOTAL_CHARGE_USD=50
SCREWFIX_TIMEOUT_SECONDS=600
TOOLSTATION_ENABLED=false
SCRAPE_FREQUENCY=monthly

# Web / CORS
VITE_API_BASE_URL=http://demo.localhost:8000
ALLOWED_ORIGINS=http://localhost:3000,http://demo.localhost:3000
EOF

echo "Wrote $ENV_FILE (production secrets + local infra URLs)."
echo "Start the replica with:  ENV_FILE=.env.prod-replica ./scripts/prod-replica-up.sh"
